name: Run GUT Tests & Deploy to itch.io

on:
  push:
    tags:
      - 'v*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Version File
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "${{ github.ref_name }}" > "i-(don't)-want-to-belive/version.txt"

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.6.2

      - name: Import project
        working-directory: i-(don't)-want-to-belive
        run: |
          godot --headless --import

      - name: Run tests
        working-directory: i-(don't)-want-to-belive
        run: |
          godot --headless -s res://addons/gut/gut_cmdln.gd -gdir=res://tests -gprefix=test_ -gexit

      - name: Export Project for Windows
        if: startsWith(github.ref, 'refs/tags/v')
        working-directory: i-(don't)-want-to-belive
        run: |
          mkdir -p ../build
          godot --headless --export-release "Windows Desktop" ../build/game.exe

      - name: Deploy to itch.io via Butler
        if: startsWith(github.ref, 'refs/tags/v')
        uses: josephbmanley/butler-publish-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
          CHANNEL: windows
          ITCH_GAME: nie-chc-uwierzy
          ITCH_USER: Zuthen
          PACKAGE: build/
          VERSION: ${{ github.ref_name }}
