name: AUTOMATED MULTIPLAYER DEPLOY

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Version File
        run: echo "${{ github.ref_name }}" > "i-(don't)-want-to-belive/version.txt"

      - name: Setup Godot (Standard Version with Templates)
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.6.2
          use-mono: false
          include-templates: true
          download-butler: false

      - name: Import project
        working-directory: i-(don't)-want-to-belive
        run: |
          godot --headless --import

      - name: Run tests
        working-directory: i-(don't)-want-to-belive
        run: |
          godot --headless -s res://addons/gut/gut_cmdln.gd -gdir=res://tests -gprefix=test_ -gexit

      - name: Export Project for Windows
        working-directory: i-(don't)-want-to-belive
        run: |
          mkdir -p ../build
          godot --headless --export-release "Windows Desktop" ../build/game.exe

      - name: Deploy to itch.io via Native Butler
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_IO_API_KEY }}
        run: |
          # Prawidłowy, oficjalny adres produkcyjny itch.io
          curl -L -o butler.zip https://itch.ovh
          unzip butler.zip
          chmod +x butler
          
          # Wysyłanie gry z folderu build utworzonego poziom wyżej względem projektu Godota
          ./butler push ../build Zuthen/nie-chc-uwierzy:windows --userversion ${{ github.ref_name }}
