name: Run GUT Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.2.2

      - name: Import project
        working-directory: i-(don't)-want-to-belive
        run: |
          godot --headless --import

      - name: Run tests
        working-directory: i-(don't)-want-to-belive
        run: |
          godot --headless --path . -s res://addons/gut/gut_cmdln.gd -gdir=res://tests -gprefix=test_ -gexit
